"""Initial tables

Revision ID: ab36a2a979a1
Revises:
Create Date: 2025-06-21 05:00:27.994528

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab36a2a979a1"
down_revision: Union[str, Sequence[str], None] = (
    None  # Changed from '636512708b04' to None
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=150), nullable=False),
        sa.Column("content", sa.VARCHAR(), nullable=False),
        sa.Column("published_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("published", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
